##
## du COMMAND PROVIDES INPUT RECORDS TO AN awk PROGRAM THAT EXAMINES EACH RECORD
## AND PRINTS ANY DIRECTORYS WHOSE SIZE EXCEEDS MINBYTES.
## THE VALUE MINBYTES MAY BE PASSED AS AN ENVIRONMENT VARIABLE ON THE COMMAND LINE, e.g.,
## MINBYTES=1000000 ducheck.sh
## DEFAULTS: CHECK THE CURRENT DIRECTORY; REPORT ANY DIRECTORYS EXCEEDING 500000K IN SIZE.
##
CHECKDIR=${CHECKDIR:-"."}
MINBYTES=${MINBYTES:-500000}
echo "ARGS: $CHECKDIR .... $MINBYTES"
du -k $CHECKDIR | awk -v mb=$MINBYTES '{if ($1 > mb) {num=$1 ; $1="" ; printf "%9d ----> %s\n",num,$0}}'
